image:
  robocomp_dependences_18.04
matrix:
  - env: SCRIPT="robocomp_compilation"
branches:
  - development
  - dev/*
script:
  - cmake .
  - make -j $(nproc)
  - sudo make install
  - sudo sh -c "echo '/opt/robocomp/lib/' >> /etc/ld.so.conf"
  - sudo ldconfig
  - python3 -m unittest discover -s tools/robocompdsl/test
